Use mock instead of a custom docker machinery to build packages
Change-Id: I068c2f427ef5dc611665fc55b3f3956247bfb113

diff --git a/scripts/common-functions b/scripts/common-functions
--- a/scripts/common-functions
+++ b/scripts/common-functions
@@ -1,13 +1,12 @@
 #!/bin/bash -xe
 
 # Function to run at the end of each rpm build (success and failure)
-# Files produced on the volume need to have their ownership changed from root.
-function finalize(){
-    chown -R $USER_ID:$GROUP_ID /data/$PROJECT_NAME /data/${PROJECT_NAME}_distro $OUTPUT_DIRECTORY
+# Cleanup temp dir where was stored src.rpm files
+function finalize() {
+    rm -rf ${TOP_DIR}
 }
 
-
-function setversionandrelease(){
+function setversionandrelease() {
     UPSTREAMVERSION=$1
     # version-release e.g 1.0.0-d7f1b849
     if [[ "$UPSTREAMVERSION" =~ (.*?)-(.+) ]] ; then
@@ -42,3 +41,18 @@ function setversionandrelease(){
         RELEASE=$UPSTREAMVERSION
     fi
 }
+
+PROJECT_NAME=$1
+OUTPUT_DIRECTORY=$2
+DATA_DIR=$3
+BASEURL=$4
+
+TOP_DIR=$(mktemp -d)
+
+mkdir -p ${TOP_DIR}/SOURCES ${TOP_DIR}/SPECS $OUTPUT_DIRECTORY
+
+trap finalize EXIT
+
+cd ${DATA_DIR}/$PROJECT_NAME
+git clean -dxf
+
